name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clean install dependencies
        run: yarn install

      - name: Configure git
        run: git config user.name "julianodgtz" && git config user.email "julianodgtz@gmail.com"
      - name: Deploy to Github Pages
        run: yarn gh-pages-deploy